# Generated by Django 4.2.4 on 2023-08-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
